### ISSUE TITLE
Check failed: error == cudaSuccess (33 vs. 0)  invalid resource handle

### ISSUE THREAD

**Issue by jeremykawahara** [jeremykawahara/ann4brains#1]
(this issue was reported via email)

When running the helloworld.py example, you get an error that says:

> I0530 14:50:14.842402  7533 solver.cpp:56] Solver scaffolding done.
> F0530 14:50:14.842481  7533 benchmark.cpp:30] Check failed: error == cudaSuccess (33 vs. 0)  invalid resource handle
> *** Check failure stack trace: ***
> Abort

This error occurs using the latest version of caffe:

```
import caffe
caffe.__version__
'1.0.0'
```
when it executes the "solver.step(1)" line in the _optimizers.py_ script.

However, you can train the model from the command line directly, which you be run directly from the "examples" directory,

`caffe train -solver proto/hello_world_solver.prototxt`

So it seems there's an issue with pycaffe on this latest version... 

However, when you use an older version of caffe,
https://github.com/BVLC/caffe/releases/tag/rc3
```
import caffe
caffe.__version__
'1.0.0-rc3'
```

the helloworld.py example works fine... 

___

So I see two workarounds right now. 1) Use an older version of caffe; or, 2) Ignore the optimizer in the ann4brains wrapper and train from the command line (the rest of the code can still be used to build the prototxt files).

If neither of options work well for you (or if you do find a solution to this pycaffe issue), please let me know.

**Comment by jeremykawahara** [comment]
Turns out this has a simple fix. In *optimizers.py*,
```python
caffe.set_mode_gpu()
```
was first called, later followed by,
```python
solver.step(1)
```
which caused this error to occurr:
> Check failed: error == cudaSuccess (33 vs. 0)  invalid resource handle

So the solution was to comment out,
```python
# caffe.set_mode_gpu()
```
as this is not needed in the code anyways (since by default, the GPU will be used). 

I've updated the code and committed this fix. So **caffe 1.0.0** should work fine now :)

**Comment by luwanxuan** [comment]
@jeremykawahara Maybe you can modify GPU ID to 0, it may work.

**Comment by du0002in** [comment]
I faced the same error after upgrading to the caffe 1.0.0. The caffe.set_mode_gpu() should be placed before any solver object is defined and initialized. 
For my case, the GPU is not used by default. Since the new caffe records the training time through cudaEvent, if GPU is not set before the solver object, when initializing the solver object, the cudaEvent is not created. If  caffe.set_mode_gpu() is only called after the solver object is initialized, the cudaEventRecord will have error since the cudaEvent is not created.
