### ISSUE TITLE
N2G Layer is missing

### ISSUE THREAD

**Issue by AdeuAndreu** [jeremykawahara/ann4brains#4]
Hello guys,

I am replicating your paper using connectivity matrices (connectomes) to see how this CNN perform for a similar problem.
I have realised that in your code there is not an implementation of the layer type Node-To-Graph Layer N2G. I wonder why there is not implementation in the layers.py. In your paper this layer is used before the fully connected layers. 

Could  you  tell me how did you perform this operation without the actual implementation of the layer? or is there some code missing ?

Thanks a lot and kind regards,

Andrés

**Comment by jeremykawahara** [comment]
Thanks for your question @AdeuAndreu !

A `Node-to-Graph` layer is equivalent to a `fully-connected` layer after an `Edge-to-Node` layer is applied. See the comments in [block #10 here](https://github.com/jeremykawahara/ann4brains/blob/master/examples/brainnetcnn.ipynb).

You can still stack additional `fully-connected` layers after the `Node-to-Graph` layer (as we did in the paper), but the interpretation of the additional `fully-connected` layers would no longer be a `Node-to-Graph` (it would be something like a `Graph-to-Graph` layer).

Hope that helps!
